schema: "./app/graphql/app_schema.graphql"
generates:
  "app/webpack/app_schema.tsx":
    documents:
      - "app/webpack/application/**/*.gql":
        skipGraphQLImport: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      scalars:
        DateTime: string
