schema: "./app/graphql/app_schema.graphql"
generates:
  "app/packs/app_schema.ts":
    documents:
      - "app/packs/application/**/*.gql"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      immutableTypes: true
      scalars:
        DateTime: string
