schema: "./app/graphql/app_schema.graphql"
generates:
  "app/webpack/app_schema.tsx":
    documents: app/webpack/application/**/*.gql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      scalars:
        DateTime: string
      withComponent: false
      withHooks: true
      withHOC: false
