inherit_gem:
  rubocop-basic: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4.5
  NewCops: enable
  Exclude:
    - config/environments/*
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - spec/spec_helper.rb

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

FactoryBot/IdSequence:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ArgumentName:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/OrderedArguments:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
