require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - config/environments/*
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - spec/spec_helper.rb

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ArgumentName:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/OrderedArguments:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false
