dependencies:
  build:
    - ruby:2.7.1

build_targets:
  - name: default
    commands:
      - bundle install
      - bundle exec rake db:test:prepare
      - bundle exec rspec

ci:
  builds:
    - name: default
      build_target: default
