query Feed {
  feed {
    entries {
      id
      tags
      photos {
        id
        url
      }
      user {
        id
        name
        avatar {
          id
          url
        }
      }
    }
  }
}
