#import "@application/fragments/billing/source.gql"

mutation SettingsBillingSourceDefault($id: ID!) {
  result: defaultBillingSource(id: $id) {
    billing {
      id
      customer {
        id
        sources {
          ...billing__source
        }
      }
    }
  }
}
