default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: playground_development

test:
  <<: *default
  database: playground_test

production:
  <<: *default
  database: playground_production
