local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'storage') %>

aws:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.aws_secret_access_key %>
  bucket: <%= ENV.fetch('AWS_BUCKET') { "playground-#{Rails.env}" } %>
  region: <%= ENV.fetch('AWS_REGION') { 'us-east-1' } %>
