#import "@application/fragments/product.gql"
#import "@application/fragments/customer.gql"

query SettingsBilling {
  billing {
    products {
      ...billing__product
    }
    customer {
      ...billing__customer
    }
  }
}
