query BillingSettings {
  billing {
    products {
      id
      name
      plans {
        id
        amount
        currency
        interval
      }
    }
    customer {
      id
      currency
      sources {
        id
        number
        brand
        exp
        default
      }
      subscriptions {
        id
        plan {
          id
          amount
          currency
          interval
        }
      }
    }
  }
}
