import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** Represents a formatted data URI. */
  DataURI: any;
  /** An ISO 8601-encoded datetime */
  DateTime: string;
  /** Represents untyped JSON */
  JSON: any;
};

/** Autogenerated return type of AttachAvatar */
export type AttachAvatarPayload = {
  readonly __typename?: 'AttachAvatarPayload';
  readonly status: Status;
};

export type Attached = {
  readonly __typename?: 'Attached';
  readonly filename: Scalars['String'];
  readonly id: Scalars['String'];
  readonly variant?: Maybe<Scalars['DataURI']>;
};


export type AttachedVariantArgs = {
  options: VariantInput;
};

export type Billing = {
  readonly __typename?: 'Billing';
  readonly customer?: Maybe<Billing__Customer>;
  readonly id: Scalars['ID'];
};

export enum Billing__Brand {
  AmericanExpress = 'AMERICAN_EXPRESS',
  DinersClub = 'DINERS_CLUB',
  Discover = 'DISCOVER',
  Jcb = 'JCB',
  Mastercard = 'MASTERCARD',
  Unionpay = 'UNIONPAY',
  Unknown = 'UNKNOWN',
  Visa = 'VISA'
}

export enum Billing__Currency {
  Cad = 'CAD',
  Eur = 'EUR',
  Usd = 'USD'
}

export type Billing__Customer = {
  readonly __typename?: 'Billing__Customer';
  readonly currency?: Maybe<Billing__Currency>;
  readonly id: Scalars['ID'];
  readonly sources: ReadonlyArray<Billing__Source>;
};

export type Billing__Source = {
  readonly __typename?: 'Billing__Source';
  readonly brand: Billing__Brand;
  readonly default: Scalars['Boolean'];
  readonly exp: Scalars['String'];
  readonly id: Scalars['ID'];
  readonly number: Scalars['String'];
};

/** Autogenerated return type of BuildBillingSource */
export type BuildBillingSourcePayload = {
  readonly __typename?: 'BuildBillingSourcePayload';
  readonly billing: Billing;
};

/** Autogenerated return type of BuildFeedComment */
export type BuildFeedCommentPayload = {
  readonly __typename?: 'BuildFeedCommentPayload';
  readonly comment?: Maybe<Feed__Comment>;
  readonly errors?: Maybe<Errors>;
  readonly status: Status;
};

/** Autogenerated return type of ChangePassword */
export type ChangePasswordPayload = {
  readonly __typename?: 'ChangePasswordPayload';
  readonly errors?: Maybe<Errors>;
  readonly status: Status;
};

/** Autogenerated return type of ChangeProfile */
export type ChangeProfilePayload = {
  readonly __typename?: 'ChangeProfilePayload';
  readonly errors?: Maybe<Errors>;
  readonly status: Status;
};



/** Autogenerated return type of DefaultBillingSource */
export type DefaultBillingSourcePayload = {
  readonly __typename?: 'DefaultBillingSourcePayload';
  readonly billing: Billing;
};

/** Autogenerated return type of DestroyBillingSource */
export type DestroyBillingSourcePayload = {
  readonly __typename?: 'DestroyBillingSourcePayload';
  readonly billing: Billing;
};

/** Autogenerated return type of DestroyNotification */
export type DestroyNotificationPayload = {
  readonly __typename?: 'DestroyNotificationPayload';
  readonly notification: Notification;
};

/** Autogenerated return type of DestroySession */
export type DestroySessionPayload = {
  readonly __typename?: 'DestroySessionPayload';
  readonly session: Session;
};

/** Autogenerated return type of DetachAvatar */
export type DetachAvatarPayload = {
  readonly __typename?: 'DetachAvatarPayload';
  readonly status: Status;
};

export type Errors = {
  readonly __typename?: 'Errors';
  readonly messages: Scalars['JSON'];
};

export type Feed = {
  readonly __typename?: 'Feed';
  readonly entries: ReadonlyArray<Feed__Entry>;
  readonly entry: Feed__Entry;
  readonly id: Scalars['ID'];
};


export type FeedEntryArgs = {
  id: Scalars['ID'];
};

export type Feed__Comment = {
  readonly __typename?: 'Feed__Comment';
  readonly id: Scalars['ID'];
  readonly message: Scalars['String'];
  readonly sent: Scalars['DateTime'];
  readonly user: User;
};

export type Feed__CommentInput = {
  readonly entryID: Scalars['ID'];
  readonly message: Scalars['String'];
};

export type Feed__Entry = {
  readonly __typename?: 'Feed__Entry';
  readonly comments: ReadonlyArray<Feed__Comment>;
  readonly id: Scalars['ID'];
  readonly liked: Scalars['Boolean'];
  readonly likes: Scalars['Int'];
  readonly photos: ReadonlyArray<Attached>;
  readonly tags: ReadonlyArray<Scalars['String']>;
  readonly user: User;
};

/** Autogenerated return type of FollowUser */
export type FollowUserPayload = {
  readonly __typename?: 'FollowUserPayload';
  readonly user: User;
};

export type Geography = {
  readonly __typename?: 'Geography';
  readonly city: Scalars['String'];
  readonly continent: Scalars['String'];
  readonly country: Scalars['String'];
  readonly id: Scalars['ID'];
  readonly latitude: Scalars['Float'];
  readonly longitude: Scalars['Float'];
  readonly postal: Scalars['String'];
  readonly region: Scalars['String'];
};


/** Autogenerated return type of LikeFeedEntry */
export type LikeFeedEntryPayload = {
  readonly __typename?: 'LikeFeedEntryPayload';
  readonly entry: Feed__Entry;
};

export type LoginInput = {
  readonly email: Scalars['String'];
  readonly password: Scalars['String'];
};

/** Autogenerated return type of LoginMutation */
export type LoginMutationPayload = {
  readonly __typename?: 'LoginMutationPayload';
  readonly errors?: Maybe<Errors>;
  readonly session?: Maybe<Session>;
  readonly status: Status;
};

/** Autogenerated return type of LogoutMutation */
export type LogoutMutationPayload = {
  readonly __typename?: 'LogoutMutationPayload';
  readonly status: Status;
};

export type Mutation = {
  readonly __typename?: 'Mutation';
  readonly attachAvatar: AttachAvatarPayload;
  readonly buildBillingSource: BuildBillingSourcePayload;
  readonly buildFeedComment: BuildFeedCommentPayload;
  readonly changePassword: ChangePasswordPayload;
  readonly changeProfile: ChangeProfilePayload;
  readonly defaultBillingSource: DefaultBillingSourcePayload;
  readonly destroyBillingSource: DestroyBillingSourcePayload;
  readonly destroyNotification: DestroyNotificationPayload;
  readonly destroySession: DestroySessionPayload;
  readonly detachAvatar: DetachAvatarPayload;
  readonly followUser: FollowUserPayload;
  readonly likeFeedEntry: LikeFeedEntryPayload;
  readonly login: LoginMutationPayload;
  readonly logout: LogoutMutationPayload;
  readonly readNotification: ReadNotificationPayload;
  readonly signup: SignupMutationPayload;
  readonly unfollowUser: UnfollowUserPayload;
  readonly unlikeFeedEntry: UnlikeFeedEntryPayload;
};


export type MutationAttachAvatarArgs = {
  id: Scalars['ID'];
};


export type MutationBuildBillingSourceArgs = {
  source: Scalars['String'];
};


export type MutationBuildFeedCommentArgs = {
  input: Feed__CommentInput;
};


export type MutationChangePasswordArgs = {
  password: PasswordInput;
};


export type MutationChangeProfileArgs = {
  input: UserInput;
};


export type MutationDefaultBillingSourceArgs = {
  id: Scalars['ID'];
};


export type MutationDestroyBillingSourceArgs = {
  id: Scalars['ID'];
};


export type MutationDestroyNotificationArgs = {
  id: Scalars['ID'];
};


export type MutationDestroySessionArgs = {
  id: Scalars['String'];
};


export type MutationFollowUserArgs = {
  id: Scalars['ID'];
};


export type MutationLikeFeedEntryArgs = {
  id: Scalars['ID'];
};


export type MutationLoginArgs = {
  input: LoginInput;
};


export type MutationReadNotificationArgs = {
  id: Scalars['ID'];
};


export type MutationSignupArgs = {
  input: SignupInput;
};


export type MutationUnfollowUserArgs = {
  id: Scalars['ID'];
};


export type MutationUnlikeFeedEntryArgs = {
  id: Scalars['ID'];
};

export type Notification = {
  readonly __typename?: 'Notification';
  readonly deleted: Scalars['Boolean'];
  readonly id: Scalars['ID'];
  readonly message: Scalars['String'];
  readonly read: Scalars['Boolean'];
  readonly sent: Scalars['DateTime'];
};

export type PasswordInput = {
  readonly current: Scalars['String'];
  readonly replacement: Scalars['String'];
};

export type Query = {
  readonly __typename?: 'Query';
  readonly billing: Billing;
  readonly feed: Feed;
  readonly me?: Maybe<User>;
  readonly notifications: ReadonlyArray<Notification>;
  readonly sessions: ReadonlyArray<Session>;
  readonly user: User;
};


export type QueryUserArgs = {
  id: Scalars['ID'];
};

/** Autogenerated return type of ReadNotification */
export type ReadNotificationPayload = {
  readonly __typename?: 'ReadNotificationPayload';
  readonly notification: Notification;
};

export type Session = {
  readonly __typename?: 'Session';
  readonly deleted: Scalars['Boolean'];
  readonly geography?: Maybe<Geography>;
  readonly id: Scalars['ID'];
  readonly ip: Scalars['String'];
  readonly seen: Scalars['DateTime'];
  readonly status: SessionStatusEnum;
  readonly user: User;
};

export enum SessionStatusEnum {
  Offline = 'OFFLINE',
  Online = 'ONLINE'
}

export type SignupInput = {
  readonly email: Scalars['String'];
  readonly name: Scalars['String'];
  readonly password: Scalars['String'];
};

/** Autogenerated return type of SignupMutation */
export type SignupMutationPayload = {
  readonly __typename?: 'SignupMutationPayload';
  readonly errors?: Maybe<Errors>;
  readonly session?: Maybe<Session>;
  readonly status: Status;
};

export enum Status {
  Ok = 'OK',
  Unprocessable = 'UNPROCESSABLE'
}

/** Autogenerated return type of UnfollowUser */
export type UnfollowUserPayload = {
  readonly __typename?: 'UnfollowUserPayload';
  readonly user: User;
};

/** Autogenerated return type of UnlikeFeedEntry */
export type UnlikeFeedEntryPayload = {
  readonly __typename?: 'UnlikeFeedEntryPayload';
  readonly entry: Feed__Entry;
};

export type User = {
  readonly __typename?: 'User';
  readonly avatar?: Maybe<Attached>;
  readonly email: Scalars['String'];
  readonly feed: Feed;
  readonly followed: Scalars['Int'];
  readonly follower: Scalars['Int'];
  readonly following: Scalars['Boolean'];
  readonly id: Scalars['ID'];
  readonly name: Scalars['String'];
};

export type UserInput = {
  readonly email: Scalars['String'];
  readonly name: Scalars['String'];
};

export type VariantInput = {
  readonly format: Variant__Format;
  readonly h: Scalars['Int'];
  readonly resize: Variant__Resize;
  readonly w: Scalars['Int'];
};

export enum Variant__Format {
  Jpeg = 'JPEG',
  Webp = 'WEBP'
}

export enum Variant__Resize {
  Fill = 'FILL',
  Fit = 'FIT'
}

export type BuildFeedCommentMutationVariables = Exact<{
  input: Feed__CommentInput;
}>;


export type BuildFeedCommentMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'BuildFeedCommentPayload' }
    & Pick<BuildFeedCommentPayload, 'status'>
    & { readonly errors?: Maybe<(
      { readonly __typename?: 'Errors' }
      & Pick<Errors, 'messages'>
    )>, readonly comment?: Maybe<(
      { readonly __typename?: 'Feed__Comment' }
      & Feed__CommentFragment
    )> }
  ) }
);

export type FeedCommentsQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type FeedCommentsQuery = (
  { readonly __typename?: 'Query' }
  & { readonly feed: (
    { readonly __typename?: 'Feed' }
    & Pick<Feed, 'id'>
    & { readonly entry: (
      { readonly __typename?: 'Feed__Entry' }
      & Pick<Feed__Entry, 'id'>
      & { readonly comments: ReadonlyArray<(
        { readonly __typename?: 'Feed__Comment' }
        & Feed__CommentFragment
      )> }
    ) }
  ) }
);

export type FeedEntryQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type FeedEntryQuery = (
  { readonly __typename?: 'Query' }
  & { readonly feed: (
    { readonly __typename?: 'Feed' }
    & Pick<Feed, 'id'>
    & { readonly entry: (
      { readonly __typename?: 'Feed__Entry' }
      & Feed__EntryFragment
    ) }
  ) }
);

export type LikeFeedEntryMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type LikeFeedEntryMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'LikeFeedEntryPayload' }
    & { readonly entry: (
      { readonly __typename?: 'Feed__Entry' }
      & Pick<Feed__Entry, 'id' | 'liked' | 'likes'>
    ) }
  ) }
);

export type UnlikeFeedEntryMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type UnlikeFeedEntryMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'UnlikeFeedEntryPayload' }
    & { readonly entry: (
      { readonly __typename?: 'Feed__Entry' }
      & Pick<Feed__Entry, 'id' | 'liked' | 'likes'>
    ) }
  ) }
);

export type FeedQueryVariables = Exact<{ [key: string]: never; }>;


export type FeedQuery = (
  { readonly __typename?: 'Query' }
  & { readonly feed: (
    { readonly __typename?: 'Feed' }
    & Pick<Feed, 'id'>
    & { readonly entries: ReadonlyArray<(
      { readonly __typename?: 'Feed__Entry' }
      & Feed__EntryFragment
    )> }
  ) }
);

export type LoginMutationVariables = Exact<{
  input: LoginInput;
}>;


export type LoginMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly login: (
    { readonly __typename?: 'LoginMutationPayload' }
    & Pick<LoginMutationPayload, 'status'>
    & { readonly session?: Maybe<(
      { readonly __typename?: 'Session' }
      & Pick<Session, 'id'>
    )>, readonly errors?: Maybe<(
      { readonly __typename?: 'Errors' }
      & Pick<Errors, 'messages'>
    )> }
  ) }
);

export type LogoutMutationVariables = Exact<{ [key: string]: never; }>;


export type LogoutMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly logout: (
    { readonly __typename?: 'LogoutMutationPayload' }
    & Pick<LogoutMutationPayload, 'status'>
  ) }
);

export type DestroyNotificationMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type DestroyNotificationMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'DestroyNotificationPayload' }
    & { readonly notification: (
      { readonly __typename?: 'Notification' }
      & Pick<Notification, 'id' | 'deleted'>
    ) }
  ) }
);

export type NotificationsQueryVariables = Exact<{ [key: string]: never; }>;


export type NotificationsQuery = (
  { readonly __typename?: 'Query' }
  & { readonly notifications: ReadonlyArray<(
    { readonly __typename?: 'Notification' }
    & NotificationFragment
  )> }
);

export type ReadNotificationMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type ReadNotificationMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'ReadNotificationPayload' }
    & { readonly notification: (
      { readonly __typename?: 'Notification' }
      & Pick<Notification, 'id' | 'read'>
    ) }
  ) }
);

export type FollowUserMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type FollowUserMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'FollowUserPayload' }
    & { readonly user: (
      { readonly __typename?: 'User' }
      & Pick<User, 'id'>
      & FollowFragment
    ) }
  ) }
);

export type ProfileQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type ProfileQuery = (
  { readonly __typename?: 'Query' }
  & { readonly user: (
    { readonly __typename?: 'User' }
    & { readonly feed: (
      { readonly __typename?: 'Feed' }
      & { readonly entries: ReadonlyArray<(
        { readonly __typename?: 'Feed__Entry' }
        & Feed__EntryFragment
      )> }
    ) }
    & UserFragment
    & FollowFragment
  ) }
);

export type UnfollowUserMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type UnfollowUserMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'UnfollowUserPayload' }
    & { readonly user: (
      { readonly __typename?: 'User' }
      & Pick<User, 'id'>
      & FollowFragment
    ) }
  ) }
);

export type SettingsAvatarAttachMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type SettingsAvatarAttachMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'AttachAvatarPayload' }
    & Pick<AttachAvatarPayload, 'status'>
  ) }
);

export type SettingsAvatarDetachMutationVariables = Exact<{ [key: string]: never; }>;


export type SettingsAvatarDetachMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'DetachAvatarPayload' }
    & Pick<DetachAvatarPayload, 'status'>
  ) }
);

export type SettingsAvatarQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsAvatarQuery = (
  { readonly __typename?: 'Query' }
  & { readonly me?: Maybe<(
    { readonly __typename?: 'User' }
    & Pick<User, 'id'>
    & { readonly avatar?: Maybe<(
      { readonly __typename?: 'Attached' }
      & Pick<Attached, 'id'>
    )> }
  )> }
);

export type SettingsBillingQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsBillingQuery = (
  { readonly __typename?: 'Query' }
  & { readonly billing: (
    { readonly __typename?: 'Billing' }
    & Pick<Billing, 'id'>
    & { readonly customer?: Maybe<(
      { readonly __typename?: 'Billing__Customer' }
      & Pick<Billing__Customer, 'id' | 'currency'>
      & { readonly sources: ReadonlyArray<(
        { readonly __typename?: 'Billing__Source' }
        & Billing__SourceFragment
      )> }
    )> }
  ) }
);

export type SettingsBillingSourceBuildMutationVariables = Exact<{
  source: Scalars['String'];
}>;


export type SettingsBillingSourceBuildMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'BuildBillingSourcePayload' }
    & { readonly billing: (
      { readonly __typename?: 'Billing' }
      & Pick<Billing, 'id'>
      & { readonly customer?: Maybe<(
        { readonly __typename?: 'Billing__Customer' }
        & Pick<Billing__Customer, 'id'>
        & { readonly sources: ReadonlyArray<(
          { readonly __typename?: 'Billing__Source' }
          & Billing__SourceFragment
        )> }
      )> }
    ) }
  ) }
);

export type SettingsBillingSourceDefaultMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type SettingsBillingSourceDefaultMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'DefaultBillingSourcePayload' }
    & { readonly billing: (
      { readonly __typename?: 'Billing' }
      & Pick<Billing, 'id'>
      & { readonly customer?: Maybe<(
        { readonly __typename?: 'Billing__Customer' }
        & Pick<Billing__Customer, 'id'>
        & { readonly sources: ReadonlyArray<(
          { readonly __typename?: 'Billing__Source' }
          & Billing__SourceFragment
        )> }
      )> }
    ) }
  ) }
);

export type SettingsBillingSourceDestroyMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type SettingsBillingSourceDestroyMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'DestroyBillingSourcePayload' }
    & { readonly billing: (
      { readonly __typename?: 'Billing' }
      & Pick<Billing, 'id'>
      & { readonly customer?: Maybe<(
        { readonly __typename?: 'Billing__Customer' }
        & Pick<Billing__Customer, 'id'>
        & { readonly sources: ReadonlyArray<(
          { readonly __typename?: 'Billing__Source' }
          & Billing__SourceFragment
        )> }
      )> }
    ) }
  ) }
);

export type SettingsPasswordMutationVariables = Exact<{
  password: PasswordInput;
}>;


export type SettingsPasswordMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'ChangePasswordPayload' }
    & Pick<ChangePasswordPayload, 'status'>
    & { readonly errors?: Maybe<(
      { readonly __typename?: 'Errors' }
      & Pick<Errors, 'messages'>
    )> }
  ) }
);

export type SettingsChangeProfileMutationVariables = Exact<{
  input: UserInput;
}>;


export type SettingsChangeProfileMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'ChangeProfilePayload' }
    & Pick<ChangeProfilePayload, 'status'>
    & { readonly errors?: Maybe<(
      { readonly __typename?: 'Errors' }
      & Pick<Errors, 'messages'>
    )> }
  ) }
);

export type SettingsProfileQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsProfileQuery = (
  { readonly __typename?: 'Query' }
  & { readonly me?: Maybe<(
    { readonly __typename?: 'User' }
    & Pick<User, 'id' | 'name' | 'email'>
  )> }
);

export type SettingsSessionsQueryVariables = Exact<{ [key: string]: never; }>;


export type SettingsSessionsQuery = (
  { readonly __typename?: 'Query' }
  & { readonly sessions: ReadonlyArray<(
    { readonly __typename?: 'Session' }
    & SessionFragment
  )> }
);

export type SettingsSessionRevokeMutationVariables = Exact<{
  id: Scalars['String'];
}>;


export type SettingsSessionRevokeMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly result: (
    { readonly __typename?: 'DestroySessionPayload' }
    & { readonly session: (
      { readonly __typename?: 'Session' }
      & Pick<Session, 'id' | 'deleted'>
    ) }
  ) }
);

export type SignupMutationVariables = Exact<{
  input: SignupInput;
}>;


export type SignupMutation = (
  { readonly __typename?: 'Mutation' }
  & { readonly signup: (
    { readonly __typename?: 'SignupMutationPayload' }
    & Pick<SignupMutationPayload, 'status'>
    & { readonly session?: Maybe<(
      { readonly __typename?: 'Session' }
      & Pick<Session, 'id'>
    )>, readonly errors?: Maybe<(
      { readonly __typename?: 'Errors' }
      & Pick<Errors, 'messages'>
    )> }
  ) }
);

export type AttachedFragment = (
  { readonly __typename?: 'Attached' }
  & Pick<Attached, 'id' | 'filename'>
);

export type Billing__SourceFragment = (
  { readonly __typename?: 'Billing__Source' }
  & Pick<Billing__Source, 'id' | 'number' | 'brand' | 'exp' | 'default'>
);

export type Feed__CommentFragment = (
  { readonly __typename?: 'Feed__Comment' }
  & Pick<Feed__Comment, 'id' | 'message' | 'sent'>
  & { readonly user: (
    { readonly __typename?: 'User' }
    & UserFragment
  ) }
);

export type Feed__EntryFragment = (
  { readonly __typename?: 'Feed__Entry' }
  & Pick<Feed__Entry, 'id' | 'tags' | 'liked' | 'likes'>
  & { readonly photos: ReadonlyArray<(
    { readonly __typename?: 'Attached' }
    & AttachedFragment
  )>, readonly user: (
    { readonly __typename?: 'User' }
    & UserFragment
  ) }
);

export type FollowFragment = (
  { readonly __typename?: 'User' }
  & Pick<User, 'following' | 'followed' | 'follower'>
);

export type GeographyFragment = (
  { readonly __typename?: 'Geography' }
  & Pick<Geography, 'id' | 'city' | 'region' | 'country' | 'postal' | 'latitude' | 'longitude'>
);

export type NotificationFragment = (
  { readonly __typename?: 'Notification' }
  & Pick<Notification, 'id' | 'message' | 'deleted' | 'read' | 'sent'>
);

export type SessionFragment = (
  { readonly __typename?: 'Session' }
  & Pick<Session, 'id' | 'ip' | 'deleted' | 'seen' | 'status'>
  & { readonly geography?: Maybe<(
    { readonly __typename?: 'Geography' }
    & GeographyFragment
  )> }
);

export type UserFragment = (
  { readonly __typename?: 'User' }
  & Pick<User, 'id' | 'name'>
  & { readonly avatar?: Maybe<(
    { readonly __typename?: 'Attached' }
    & AttachedFragment
  )> }
);

export const Billing__SourceFragmentDoc = gql`
    fragment billing__source on Billing__Source {
  id
  number
  brand
  exp
  default
}
    `;
export const AttachedFragmentDoc = gql`
    fragment attached on Attached {
  id
  filename
}
    `;
export const UserFragmentDoc = gql`
    fragment user on User {
  id
  name
  avatar {
    ...attached
  }
}
    ${AttachedFragmentDoc}`;
export const Feed__CommentFragmentDoc = gql`
    fragment feed__comment on Feed__Comment {
  id
  message
  sent
  user {
    ...user
  }
}
    ${UserFragmentDoc}`;
export const Feed__EntryFragmentDoc = gql`
    fragment feed__entry on Feed__Entry {
  id
  tags
  liked
  likes
  photos {
    ...attached
  }
  user {
    ...user
  }
}
    ${AttachedFragmentDoc}
${UserFragmentDoc}`;
export const FollowFragmentDoc = gql`
    fragment follow on User {
  following
  followed
  follower
}
    `;
export const NotificationFragmentDoc = gql`
    fragment notification on Notification {
  id
  message
  deleted
  read
  sent
}
    `;
export const GeographyFragmentDoc = gql`
    fragment geography on Geography {
  id
  city
  region
  country
  postal
  latitude
  longitude
}
    `;
export const SessionFragmentDoc = gql`
    fragment session on Session {
  id
  ip
  deleted
  seen
  status
  geography {
    ...geography
  }
}
    ${GeographyFragmentDoc}`;
export const BuildFeedCommentDocument = gql`
    mutation BuildFeedComment($input: Feed__CommentInput!) {
  result: buildFeedComment(input: $input) {
    status
    errors {
      messages
    }
    comment {
      ...feed__comment
    }
  }
}
    ${Feed__CommentFragmentDoc}`;
export type BuildFeedCommentMutationFn = Apollo.MutationFunction<BuildFeedCommentMutation, BuildFeedCommentMutationVariables>;

/**
 * __useBuildFeedCommentMutation__
 *
 * To run a mutation, you first call `useBuildFeedCommentMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useBuildFeedCommentMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [buildFeedCommentMutation, { data, loading, error }] = useBuildFeedCommentMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useBuildFeedCommentMutation(baseOptions?: Apollo.MutationHookOptions<BuildFeedCommentMutation, BuildFeedCommentMutationVariables>) {
        return Apollo.useMutation<BuildFeedCommentMutation, BuildFeedCommentMutationVariables>(BuildFeedCommentDocument, baseOptions);
      }
export type BuildFeedCommentMutationHookResult = ReturnType<typeof useBuildFeedCommentMutation>;
export type BuildFeedCommentMutationResult = Apollo.MutationResult<BuildFeedCommentMutation>;
export type BuildFeedCommentMutationOptions = Apollo.BaseMutationOptions<BuildFeedCommentMutation, BuildFeedCommentMutationVariables>;
export const FeedCommentsDocument = gql`
    query FeedComments($id: ID!) {
  feed {
    id
    entry(id: $id) {
      id
      comments {
        ...feed__comment
      }
    }
  }
}
    ${Feed__CommentFragmentDoc}`;

/**
 * __useFeedCommentsQuery__
 *
 * To run a query within a React component, call `useFeedCommentsQuery` and pass it any options that fit your needs.
 * When your component renders, `useFeedCommentsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFeedCommentsQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useFeedCommentsQuery(baseOptions: Apollo.QueryHookOptions<FeedCommentsQuery, FeedCommentsQueryVariables>) {
        return Apollo.useQuery<FeedCommentsQuery, FeedCommentsQueryVariables>(FeedCommentsDocument, baseOptions);
      }
export function useFeedCommentsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FeedCommentsQuery, FeedCommentsQueryVariables>) {
          return Apollo.useLazyQuery<FeedCommentsQuery, FeedCommentsQueryVariables>(FeedCommentsDocument, baseOptions);
        }
export type FeedCommentsQueryHookResult = ReturnType<typeof useFeedCommentsQuery>;
export type FeedCommentsLazyQueryHookResult = ReturnType<typeof useFeedCommentsLazyQuery>;
export type FeedCommentsQueryResult = Apollo.QueryResult<FeedCommentsQuery, FeedCommentsQueryVariables>;
export const FeedEntryDocument = gql`
    query FeedEntry($id: ID!) {
  feed {
    id
    entry(id: $id) {
      ...feed__entry
    }
  }
}
    ${Feed__EntryFragmentDoc}`;

/**
 * __useFeedEntryQuery__
 *
 * To run a query within a React component, call `useFeedEntryQuery` and pass it any options that fit your needs.
 * When your component renders, `useFeedEntryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFeedEntryQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useFeedEntryQuery(baseOptions: Apollo.QueryHookOptions<FeedEntryQuery, FeedEntryQueryVariables>) {
        return Apollo.useQuery<FeedEntryQuery, FeedEntryQueryVariables>(FeedEntryDocument, baseOptions);
      }
export function useFeedEntryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FeedEntryQuery, FeedEntryQueryVariables>) {
          return Apollo.useLazyQuery<FeedEntryQuery, FeedEntryQueryVariables>(FeedEntryDocument, baseOptions);
        }
export type FeedEntryQueryHookResult = ReturnType<typeof useFeedEntryQuery>;
export type FeedEntryLazyQueryHookResult = ReturnType<typeof useFeedEntryLazyQuery>;
export type FeedEntryQueryResult = Apollo.QueryResult<FeedEntryQuery, FeedEntryQueryVariables>;
export const LikeFeedEntryDocument = gql`
    mutation LikeFeedEntry($id: ID!) {
  result: likeFeedEntry(id: $id) {
    entry {
      id
      liked
      likes
    }
  }
}
    `;
export type LikeFeedEntryMutationFn = Apollo.MutationFunction<LikeFeedEntryMutation, LikeFeedEntryMutationVariables>;

/**
 * __useLikeFeedEntryMutation__
 *
 * To run a mutation, you first call `useLikeFeedEntryMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLikeFeedEntryMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [likeFeedEntryMutation, { data, loading, error }] = useLikeFeedEntryMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useLikeFeedEntryMutation(baseOptions?: Apollo.MutationHookOptions<LikeFeedEntryMutation, LikeFeedEntryMutationVariables>) {
        return Apollo.useMutation<LikeFeedEntryMutation, LikeFeedEntryMutationVariables>(LikeFeedEntryDocument, baseOptions);
      }
export type LikeFeedEntryMutationHookResult = ReturnType<typeof useLikeFeedEntryMutation>;
export type LikeFeedEntryMutationResult = Apollo.MutationResult<LikeFeedEntryMutation>;
export type LikeFeedEntryMutationOptions = Apollo.BaseMutationOptions<LikeFeedEntryMutation, LikeFeedEntryMutationVariables>;
export const UnlikeFeedEntryDocument = gql`
    mutation UnlikeFeedEntry($id: ID!) {
  result: unlikeFeedEntry(id: $id) {
    entry {
      id
      liked
      likes
    }
  }
}
    `;
export type UnlikeFeedEntryMutationFn = Apollo.MutationFunction<UnlikeFeedEntryMutation, UnlikeFeedEntryMutationVariables>;

/**
 * __useUnlikeFeedEntryMutation__
 *
 * To run a mutation, you first call `useUnlikeFeedEntryMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUnlikeFeedEntryMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [unlikeFeedEntryMutation, { data, loading, error }] = useUnlikeFeedEntryMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useUnlikeFeedEntryMutation(baseOptions?: Apollo.MutationHookOptions<UnlikeFeedEntryMutation, UnlikeFeedEntryMutationVariables>) {
        return Apollo.useMutation<UnlikeFeedEntryMutation, UnlikeFeedEntryMutationVariables>(UnlikeFeedEntryDocument, baseOptions);
      }
export type UnlikeFeedEntryMutationHookResult = ReturnType<typeof useUnlikeFeedEntryMutation>;
export type UnlikeFeedEntryMutationResult = Apollo.MutationResult<UnlikeFeedEntryMutation>;
export type UnlikeFeedEntryMutationOptions = Apollo.BaseMutationOptions<UnlikeFeedEntryMutation, UnlikeFeedEntryMutationVariables>;
export const FeedDocument = gql`
    query Feed {
  feed {
    id
    entries {
      ...feed__entry
    }
  }
}
    ${Feed__EntryFragmentDoc}`;

/**
 * __useFeedQuery__
 *
 * To run a query within a React component, call `useFeedQuery` and pass it any options that fit your needs.
 * When your component renders, `useFeedQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFeedQuery({
 *   variables: {
 *   },
 * });
 */
export function useFeedQuery(baseOptions?: Apollo.QueryHookOptions<FeedQuery, FeedQueryVariables>) {
        return Apollo.useQuery<FeedQuery, FeedQueryVariables>(FeedDocument, baseOptions);
      }
export function useFeedLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FeedQuery, FeedQueryVariables>) {
          return Apollo.useLazyQuery<FeedQuery, FeedQueryVariables>(FeedDocument, baseOptions);
        }
export type FeedQueryHookResult = ReturnType<typeof useFeedQuery>;
export type FeedLazyQueryHookResult = ReturnType<typeof useFeedLazyQuery>;
export type FeedQueryResult = Apollo.QueryResult<FeedQuery, FeedQueryVariables>;
export const LoginDocument = gql`
    mutation Login($input: LoginInput!) {
  login(input: $input) {
    status
    session {
      id
    }
    errors {
      messages
    }
  }
}
    `;
export type LoginMutationFn = Apollo.MutationFunction<LoginMutation, LoginMutationVariables>;

/**
 * __useLoginMutation__
 *
 * To run a mutation, you first call `useLoginMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLoginMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [loginMutation, { data, loading, error }] = useLoginMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useLoginMutation(baseOptions?: Apollo.MutationHookOptions<LoginMutation, LoginMutationVariables>) {
        return Apollo.useMutation<LoginMutation, LoginMutationVariables>(LoginDocument, baseOptions);
      }
export type LoginMutationHookResult = ReturnType<typeof useLoginMutation>;
export type LoginMutationResult = Apollo.MutationResult<LoginMutation>;
export type LoginMutationOptions = Apollo.BaseMutationOptions<LoginMutation, LoginMutationVariables>;
export const LogoutDocument = gql`
    mutation Logout {
  logout {
    status
  }
}
    `;
export type LogoutMutationFn = Apollo.MutationFunction<LogoutMutation, LogoutMutationVariables>;

/**
 * __useLogoutMutation__
 *
 * To run a mutation, you first call `useLogoutMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLogoutMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [logoutMutation, { data, loading, error }] = useLogoutMutation({
 *   variables: {
 *   },
 * });
 */
export function useLogoutMutation(baseOptions?: Apollo.MutationHookOptions<LogoutMutation, LogoutMutationVariables>) {
        return Apollo.useMutation<LogoutMutation, LogoutMutationVariables>(LogoutDocument, baseOptions);
      }
export type LogoutMutationHookResult = ReturnType<typeof useLogoutMutation>;
export type LogoutMutationResult = Apollo.MutationResult<LogoutMutation>;
export type LogoutMutationOptions = Apollo.BaseMutationOptions<LogoutMutation, LogoutMutationVariables>;
export const DestroyNotificationDocument = gql`
    mutation DestroyNotification($id: ID!) {
  result: destroyNotification(id: $id) {
    notification {
      id
      deleted
    }
  }
}
    `;
export type DestroyNotificationMutationFn = Apollo.MutationFunction<DestroyNotificationMutation, DestroyNotificationMutationVariables>;

/**
 * __useDestroyNotificationMutation__
 *
 * To run a mutation, you first call `useDestroyNotificationMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDestroyNotificationMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [destroyNotificationMutation, { data, loading, error }] = useDestroyNotificationMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDestroyNotificationMutation(baseOptions?: Apollo.MutationHookOptions<DestroyNotificationMutation, DestroyNotificationMutationVariables>) {
        return Apollo.useMutation<DestroyNotificationMutation, DestroyNotificationMutationVariables>(DestroyNotificationDocument, baseOptions);
      }
export type DestroyNotificationMutationHookResult = ReturnType<typeof useDestroyNotificationMutation>;
export type DestroyNotificationMutationResult = Apollo.MutationResult<DestroyNotificationMutation>;
export type DestroyNotificationMutationOptions = Apollo.BaseMutationOptions<DestroyNotificationMutation, DestroyNotificationMutationVariables>;
export const NotificationsDocument = gql`
    query Notifications {
  notifications {
    ...notification
  }
}
    ${NotificationFragmentDoc}`;

/**
 * __useNotificationsQuery__
 *
 * To run a query within a React component, call `useNotificationsQuery` and pass it any options that fit your needs.
 * When your component renders, `useNotificationsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNotificationsQuery({
 *   variables: {
 *   },
 * });
 */
export function useNotificationsQuery(baseOptions?: Apollo.QueryHookOptions<NotificationsQuery, NotificationsQueryVariables>) {
        return Apollo.useQuery<NotificationsQuery, NotificationsQueryVariables>(NotificationsDocument, baseOptions);
      }
export function useNotificationsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NotificationsQuery, NotificationsQueryVariables>) {
          return Apollo.useLazyQuery<NotificationsQuery, NotificationsQueryVariables>(NotificationsDocument, baseOptions);
        }
export type NotificationsQueryHookResult = ReturnType<typeof useNotificationsQuery>;
export type NotificationsLazyQueryHookResult = ReturnType<typeof useNotificationsLazyQuery>;
export type NotificationsQueryResult = Apollo.QueryResult<NotificationsQuery, NotificationsQueryVariables>;
export const ReadNotificationDocument = gql`
    mutation ReadNotification($id: ID!) {
  result: readNotification(id: $id) {
    notification {
      id
      read
    }
  }
}
    `;
export type ReadNotificationMutationFn = Apollo.MutationFunction<ReadNotificationMutation, ReadNotificationMutationVariables>;

/**
 * __useReadNotificationMutation__
 *
 * To run a mutation, you first call `useReadNotificationMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useReadNotificationMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [readNotificationMutation, { data, loading, error }] = useReadNotificationMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useReadNotificationMutation(baseOptions?: Apollo.MutationHookOptions<ReadNotificationMutation, ReadNotificationMutationVariables>) {
        return Apollo.useMutation<ReadNotificationMutation, ReadNotificationMutationVariables>(ReadNotificationDocument, baseOptions);
      }
export type ReadNotificationMutationHookResult = ReturnType<typeof useReadNotificationMutation>;
export type ReadNotificationMutationResult = Apollo.MutationResult<ReadNotificationMutation>;
export type ReadNotificationMutationOptions = Apollo.BaseMutationOptions<ReadNotificationMutation, ReadNotificationMutationVariables>;
export const FollowUserDocument = gql`
    mutation FollowUser($id: ID!) {
  result: followUser(id: $id) {
    user {
      id
      ...follow
    }
  }
}
    ${FollowFragmentDoc}`;
export type FollowUserMutationFn = Apollo.MutationFunction<FollowUserMutation, FollowUserMutationVariables>;

/**
 * __useFollowUserMutation__
 *
 * To run a mutation, you first call `useFollowUserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useFollowUserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [followUserMutation, { data, loading, error }] = useFollowUserMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useFollowUserMutation(baseOptions?: Apollo.MutationHookOptions<FollowUserMutation, FollowUserMutationVariables>) {
        return Apollo.useMutation<FollowUserMutation, FollowUserMutationVariables>(FollowUserDocument, baseOptions);
      }
export type FollowUserMutationHookResult = ReturnType<typeof useFollowUserMutation>;
export type FollowUserMutationResult = Apollo.MutationResult<FollowUserMutation>;
export type FollowUserMutationOptions = Apollo.BaseMutationOptions<FollowUserMutation, FollowUserMutationVariables>;
export const ProfileDocument = gql`
    query Profile($id: ID!) {
  user(id: $id) {
    ...user
    ...follow
    feed {
      entries {
        ...feed__entry
      }
    }
  }
}
    ${UserFragmentDoc}
${FollowFragmentDoc}
${Feed__EntryFragmentDoc}`;

/**
 * __useProfileQuery__
 *
 * To run a query within a React component, call `useProfileQuery` and pass it any options that fit your needs.
 * When your component renders, `useProfileQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useProfileQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useProfileQuery(baseOptions: Apollo.QueryHookOptions<ProfileQuery, ProfileQueryVariables>) {
        return Apollo.useQuery<ProfileQuery, ProfileQueryVariables>(ProfileDocument, baseOptions);
      }
export function useProfileLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ProfileQuery, ProfileQueryVariables>) {
          return Apollo.useLazyQuery<ProfileQuery, ProfileQueryVariables>(ProfileDocument, baseOptions);
        }
export type ProfileQueryHookResult = ReturnType<typeof useProfileQuery>;
export type ProfileLazyQueryHookResult = ReturnType<typeof useProfileLazyQuery>;
export type ProfileQueryResult = Apollo.QueryResult<ProfileQuery, ProfileQueryVariables>;
export const UnfollowUserDocument = gql`
    mutation UnfollowUser($id: ID!) {
  result: unfollowUser(id: $id) {
    user {
      id
      ...follow
    }
  }
}
    ${FollowFragmentDoc}`;
export type UnfollowUserMutationFn = Apollo.MutationFunction<UnfollowUserMutation, UnfollowUserMutationVariables>;

/**
 * __useUnfollowUserMutation__
 *
 * To run a mutation, you first call `useUnfollowUserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUnfollowUserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [unfollowUserMutation, { data, loading, error }] = useUnfollowUserMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useUnfollowUserMutation(baseOptions?: Apollo.MutationHookOptions<UnfollowUserMutation, UnfollowUserMutationVariables>) {
        return Apollo.useMutation<UnfollowUserMutation, UnfollowUserMutationVariables>(UnfollowUserDocument, baseOptions);
      }
export type UnfollowUserMutationHookResult = ReturnType<typeof useUnfollowUserMutation>;
export type UnfollowUserMutationResult = Apollo.MutationResult<UnfollowUserMutation>;
export type UnfollowUserMutationOptions = Apollo.BaseMutationOptions<UnfollowUserMutation, UnfollowUserMutationVariables>;
export const SettingsAvatarAttachDocument = gql`
    mutation SettingsAvatarAttach($id: ID!) {
  result: attachAvatar(id: $id) {
    status
  }
}
    `;
export type SettingsAvatarAttachMutationFn = Apollo.MutationFunction<SettingsAvatarAttachMutation, SettingsAvatarAttachMutationVariables>;

/**
 * __useSettingsAvatarAttachMutation__
 *
 * To run a mutation, you first call `useSettingsAvatarAttachMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsAvatarAttachMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsAvatarAttachMutation, { data, loading, error }] = useSettingsAvatarAttachMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useSettingsAvatarAttachMutation(baseOptions?: Apollo.MutationHookOptions<SettingsAvatarAttachMutation, SettingsAvatarAttachMutationVariables>) {
        return Apollo.useMutation<SettingsAvatarAttachMutation, SettingsAvatarAttachMutationVariables>(SettingsAvatarAttachDocument, baseOptions);
      }
export type SettingsAvatarAttachMutationHookResult = ReturnType<typeof useSettingsAvatarAttachMutation>;
export type SettingsAvatarAttachMutationResult = Apollo.MutationResult<SettingsAvatarAttachMutation>;
export type SettingsAvatarAttachMutationOptions = Apollo.BaseMutationOptions<SettingsAvatarAttachMutation, SettingsAvatarAttachMutationVariables>;
export const SettingsAvatarDetachDocument = gql`
    mutation SettingsAvatarDetach {
  result: detachAvatar {
    status
  }
}
    `;
export type SettingsAvatarDetachMutationFn = Apollo.MutationFunction<SettingsAvatarDetachMutation, SettingsAvatarDetachMutationVariables>;

/**
 * __useSettingsAvatarDetachMutation__
 *
 * To run a mutation, you first call `useSettingsAvatarDetachMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsAvatarDetachMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsAvatarDetachMutation, { data, loading, error }] = useSettingsAvatarDetachMutation({
 *   variables: {
 *   },
 * });
 */
export function useSettingsAvatarDetachMutation(baseOptions?: Apollo.MutationHookOptions<SettingsAvatarDetachMutation, SettingsAvatarDetachMutationVariables>) {
        return Apollo.useMutation<SettingsAvatarDetachMutation, SettingsAvatarDetachMutationVariables>(SettingsAvatarDetachDocument, baseOptions);
      }
export type SettingsAvatarDetachMutationHookResult = ReturnType<typeof useSettingsAvatarDetachMutation>;
export type SettingsAvatarDetachMutationResult = Apollo.MutationResult<SettingsAvatarDetachMutation>;
export type SettingsAvatarDetachMutationOptions = Apollo.BaseMutationOptions<SettingsAvatarDetachMutation, SettingsAvatarDetachMutationVariables>;
export const SettingsAvatarDocument = gql`
    query SettingsAvatar {
  me {
    id
    avatar {
      id
    }
  }
}
    `;

/**
 * __useSettingsAvatarQuery__
 *
 * To run a query within a React component, call `useSettingsAvatarQuery` and pass it any options that fit your needs.
 * When your component renders, `useSettingsAvatarQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSettingsAvatarQuery({
 *   variables: {
 *   },
 * });
 */
export function useSettingsAvatarQuery(baseOptions?: Apollo.QueryHookOptions<SettingsAvatarQuery, SettingsAvatarQueryVariables>) {
        return Apollo.useQuery<SettingsAvatarQuery, SettingsAvatarQueryVariables>(SettingsAvatarDocument, baseOptions);
      }
export function useSettingsAvatarLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SettingsAvatarQuery, SettingsAvatarQueryVariables>) {
          return Apollo.useLazyQuery<SettingsAvatarQuery, SettingsAvatarQueryVariables>(SettingsAvatarDocument, baseOptions);
        }
export type SettingsAvatarQueryHookResult = ReturnType<typeof useSettingsAvatarQuery>;
export type SettingsAvatarLazyQueryHookResult = ReturnType<typeof useSettingsAvatarLazyQuery>;
export type SettingsAvatarQueryResult = Apollo.QueryResult<SettingsAvatarQuery, SettingsAvatarQueryVariables>;
export const SettingsBillingDocument = gql`
    query SettingsBilling {
  billing {
    id
    customer {
      id
      currency
      sources {
        ...billing__source
      }
    }
  }
}
    ${Billing__SourceFragmentDoc}`;

/**
 * __useSettingsBillingQuery__
 *
 * To run a query within a React component, call `useSettingsBillingQuery` and pass it any options that fit your needs.
 * When your component renders, `useSettingsBillingQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSettingsBillingQuery({
 *   variables: {
 *   },
 * });
 */
export function useSettingsBillingQuery(baseOptions?: Apollo.QueryHookOptions<SettingsBillingQuery, SettingsBillingQueryVariables>) {
        return Apollo.useQuery<SettingsBillingQuery, SettingsBillingQueryVariables>(SettingsBillingDocument, baseOptions);
      }
export function useSettingsBillingLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SettingsBillingQuery, SettingsBillingQueryVariables>) {
          return Apollo.useLazyQuery<SettingsBillingQuery, SettingsBillingQueryVariables>(SettingsBillingDocument, baseOptions);
        }
export type SettingsBillingQueryHookResult = ReturnType<typeof useSettingsBillingQuery>;
export type SettingsBillingLazyQueryHookResult = ReturnType<typeof useSettingsBillingLazyQuery>;
export type SettingsBillingQueryResult = Apollo.QueryResult<SettingsBillingQuery, SettingsBillingQueryVariables>;
export const SettingsBillingSourceBuildDocument = gql`
    mutation SettingsBillingSourceBuild($source: String!) {
  result: buildBillingSource(source: $source) {
    billing {
      id
      customer {
        id
        sources {
          ...billing__source
        }
      }
    }
  }
}
    ${Billing__SourceFragmentDoc}`;
export type SettingsBillingSourceBuildMutationFn = Apollo.MutationFunction<SettingsBillingSourceBuildMutation, SettingsBillingSourceBuildMutationVariables>;

/**
 * __useSettingsBillingSourceBuildMutation__
 *
 * To run a mutation, you first call `useSettingsBillingSourceBuildMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsBillingSourceBuildMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsBillingSourceBuildMutation, { data, loading, error }] = useSettingsBillingSourceBuildMutation({
 *   variables: {
 *      source: // value for 'source'
 *   },
 * });
 */
export function useSettingsBillingSourceBuildMutation(baseOptions?: Apollo.MutationHookOptions<SettingsBillingSourceBuildMutation, SettingsBillingSourceBuildMutationVariables>) {
        return Apollo.useMutation<SettingsBillingSourceBuildMutation, SettingsBillingSourceBuildMutationVariables>(SettingsBillingSourceBuildDocument, baseOptions);
      }
export type SettingsBillingSourceBuildMutationHookResult = ReturnType<typeof useSettingsBillingSourceBuildMutation>;
export type SettingsBillingSourceBuildMutationResult = Apollo.MutationResult<SettingsBillingSourceBuildMutation>;
export type SettingsBillingSourceBuildMutationOptions = Apollo.BaseMutationOptions<SettingsBillingSourceBuildMutation, SettingsBillingSourceBuildMutationVariables>;
export const SettingsBillingSourceDefaultDocument = gql`
    mutation SettingsBillingSourceDefault($id: ID!) {
  result: defaultBillingSource(id: $id) {
    billing {
      id
      customer {
        id
        sources {
          ...billing__source
        }
      }
    }
  }
}
    ${Billing__SourceFragmentDoc}`;
export type SettingsBillingSourceDefaultMutationFn = Apollo.MutationFunction<SettingsBillingSourceDefaultMutation, SettingsBillingSourceDefaultMutationVariables>;

/**
 * __useSettingsBillingSourceDefaultMutation__
 *
 * To run a mutation, you first call `useSettingsBillingSourceDefaultMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsBillingSourceDefaultMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsBillingSourceDefaultMutation, { data, loading, error }] = useSettingsBillingSourceDefaultMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useSettingsBillingSourceDefaultMutation(baseOptions?: Apollo.MutationHookOptions<SettingsBillingSourceDefaultMutation, SettingsBillingSourceDefaultMutationVariables>) {
        return Apollo.useMutation<SettingsBillingSourceDefaultMutation, SettingsBillingSourceDefaultMutationVariables>(SettingsBillingSourceDefaultDocument, baseOptions);
      }
export type SettingsBillingSourceDefaultMutationHookResult = ReturnType<typeof useSettingsBillingSourceDefaultMutation>;
export type SettingsBillingSourceDefaultMutationResult = Apollo.MutationResult<SettingsBillingSourceDefaultMutation>;
export type SettingsBillingSourceDefaultMutationOptions = Apollo.BaseMutationOptions<SettingsBillingSourceDefaultMutation, SettingsBillingSourceDefaultMutationVariables>;
export const SettingsBillingSourceDestroyDocument = gql`
    mutation SettingsBillingSourceDestroy($id: ID!) {
  result: destroyBillingSource(id: $id) {
    billing {
      id
      customer {
        id
        sources {
          ...billing__source
        }
      }
    }
  }
}
    ${Billing__SourceFragmentDoc}`;
export type SettingsBillingSourceDestroyMutationFn = Apollo.MutationFunction<SettingsBillingSourceDestroyMutation, SettingsBillingSourceDestroyMutationVariables>;

/**
 * __useSettingsBillingSourceDestroyMutation__
 *
 * To run a mutation, you first call `useSettingsBillingSourceDestroyMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsBillingSourceDestroyMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsBillingSourceDestroyMutation, { data, loading, error }] = useSettingsBillingSourceDestroyMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useSettingsBillingSourceDestroyMutation(baseOptions?: Apollo.MutationHookOptions<SettingsBillingSourceDestroyMutation, SettingsBillingSourceDestroyMutationVariables>) {
        return Apollo.useMutation<SettingsBillingSourceDestroyMutation, SettingsBillingSourceDestroyMutationVariables>(SettingsBillingSourceDestroyDocument, baseOptions);
      }
export type SettingsBillingSourceDestroyMutationHookResult = ReturnType<typeof useSettingsBillingSourceDestroyMutation>;
export type SettingsBillingSourceDestroyMutationResult = Apollo.MutationResult<SettingsBillingSourceDestroyMutation>;
export type SettingsBillingSourceDestroyMutationOptions = Apollo.BaseMutationOptions<SettingsBillingSourceDestroyMutation, SettingsBillingSourceDestroyMutationVariables>;
export const SettingsPasswordDocument = gql`
    mutation SettingsPassword($password: PasswordInput!) {
  result: changePassword(password: $password) {
    status
    errors {
      messages
    }
  }
}
    `;
export type SettingsPasswordMutationFn = Apollo.MutationFunction<SettingsPasswordMutation, SettingsPasswordMutationVariables>;

/**
 * __useSettingsPasswordMutation__
 *
 * To run a mutation, you first call `useSettingsPasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsPasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsPasswordMutation, { data, loading, error }] = useSettingsPasswordMutation({
 *   variables: {
 *      password: // value for 'password'
 *   },
 * });
 */
export function useSettingsPasswordMutation(baseOptions?: Apollo.MutationHookOptions<SettingsPasswordMutation, SettingsPasswordMutationVariables>) {
        return Apollo.useMutation<SettingsPasswordMutation, SettingsPasswordMutationVariables>(SettingsPasswordDocument, baseOptions);
      }
export type SettingsPasswordMutationHookResult = ReturnType<typeof useSettingsPasswordMutation>;
export type SettingsPasswordMutationResult = Apollo.MutationResult<SettingsPasswordMutation>;
export type SettingsPasswordMutationOptions = Apollo.BaseMutationOptions<SettingsPasswordMutation, SettingsPasswordMutationVariables>;
export const SettingsChangeProfileDocument = gql`
    mutation SettingsChangeProfile($input: UserInput!) {
  result: changeProfile(input: $input) {
    status
    errors {
      messages
    }
  }
}
    `;
export type SettingsChangeProfileMutationFn = Apollo.MutationFunction<SettingsChangeProfileMutation, SettingsChangeProfileMutationVariables>;

/**
 * __useSettingsChangeProfileMutation__
 *
 * To run a mutation, you first call `useSettingsChangeProfileMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsChangeProfileMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsChangeProfileMutation, { data, loading, error }] = useSettingsChangeProfileMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useSettingsChangeProfileMutation(baseOptions?: Apollo.MutationHookOptions<SettingsChangeProfileMutation, SettingsChangeProfileMutationVariables>) {
        return Apollo.useMutation<SettingsChangeProfileMutation, SettingsChangeProfileMutationVariables>(SettingsChangeProfileDocument, baseOptions);
      }
export type SettingsChangeProfileMutationHookResult = ReturnType<typeof useSettingsChangeProfileMutation>;
export type SettingsChangeProfileMutationResult = Apollo.MutationResult<SettingsChangeProfileMutation>;
export type SettingsChangeProfileMutationOptions = Apollo.BaseMutationOptions<SettingsChangeProfileMutation, SettingsChangeProfileMutationVariables>;
export const SettingsProfileDocument = gql`
    query SettingsProfile {
  me {
    id
    name
    email
  }
}
    `;

/**
 * __useSettingsProfileQuery__
 *
 * To run a query within a React component, call `useSettingsProfileQuery` and pass it any options that fit your needs.
 * When your component renders, `useSettingsProfileQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSettingsProfileQuery({
 *   variables: {
 *   },
 * });
 */
export function useSettingsProfileQuery(baseOptions?: Apollo.QueryHookOptions<SettingsProfileQuery, SettingsProfileQueryVariables>) {
        return Apollo.useQuery<SettingsProfileQuery, SettingsProfileQueryVariables>(SettingsProfileDocument, baseOptions);
      }
export function useSettingsProfileLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SettingsProfileQuery, SettingsProfileQueryVariables>) {
          return Apollo.useLazyQuery<SettingsProfileQuery, SettingsProfileQueryVariables>(SettingsProfileDocument, baseOptions);
        }
export type SettingsProfileQueryHookResult = ReturnType<typeof useSettingsProfileQuery>;
export type SettingsProfileLazyQueryHookResult = ReturnType<typeof useSettingsProfileLazyQuery>;
export type SettingsProfileQueryResult = Apollo.QueryResult<SettingsProfileQuery, SettingsProfileQueryVariables>;
export const SettingsSessionsDocument = gql`
    query SettingsSessions {
  sessions {
    ...session
  }
}
    ${SessionFragmentDoc}`;

/**
 * __useSettingsSessionsQuery__
 *
 * To run a query within a React component, call `useSettingsSessionsQuery` and pass it any options that fit your needs.
 * When your component renders, `useSettingsSessionsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSettingsSessionsQuery({
 *   variables: {
 *   },
 * });
 */
export function useSettingsSessionsQuery(baseOptions?: Apollo.QueryHookOptions<SettingsSessionsQuery, SettingsSessionsQueryVariables>) {
        return Apollo.useQuery<SettingsSessionsQuery, SettingsSessionsQueryVariables>(SettingsSessionsDocument, baseOptions);
      }
export function useSettingsSessionsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SettingsSessionsQuery, SettingsSessionsQueryVariables>) {
          return Apollo.useLazyQuery<SettingsSessionsQuery, SettingsSessionsQueryVariables>(SettingsSessionsDocument, baseOptions);
        }
export type SettingsSessionsQueryHookResult = ReturnType<typeof useSettingsSessionsQuery>;
export type SettingsSessionsLazyQueryHookResult = ReturnType<typeof useSettingsSessionsLazyQuery>;
export type SettingsSessionsQueryResult = Apollo.QueryResult<SettingsSessionsQuery, SettingsSessionsQueryVariables>;
export const SettingsSessionRevokeDocument = gql`
    mutation SettingsSessionRevoke($id: String!) {
  result: destroySession(id: $id) {
    session {
      id
      deleted
    }
  }
}
    `;
export type SettingsSessionRevokeMutationFn = Apollo.MutationFunction<SettingsSessionRevokeMutation, SettingsSessionRevokeMutationVariables>;

/**
 * __useSettingsSessionRevokeMutation__
 *
 * To run a mutation, you first call `useSettingsSessionRevokeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSettingsSessionRevokeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [settingsSessionRevokeMutation, { data, loading, error }] = useSettingsSessionRevokeMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useSettingsSessionRevokeMutation(baseOptions?: Apollo.MutationHookOptions<SettingsSessionRevokeMutation, SettingsSessionRevokeMutationVariables>) {
        return Apollo.useMutation<SettingsSessionRevokeMutation, SettingsSessionRevokeMutationVariables>(SettingsSessionRevokeDocument, baseOptions);
      }
export type SettingsSessionRevokeMutationHookResult = ReturnType<typeof useSettingsSessionRevokeMutation>;
export type SettingsSessionRevokeMutationResult = Apollo.MutationResult<SettingsSessionRevokeMutation>;
export type SettingsSessionRevokeMutationOptions = Apollo.BaseMutationOptions<SettingsSessionRevokeMutation, SettingsSessionRevokeMutationVariables>;
export const SignupDocument = gql`
    mutation Signup($input: SignupInput!) {
  signup(input: $input) {
    status
    session {
      id
    }
    errors {
      messages
    }
  }
}
    `;
export type SignupMutationFn = Apollo.MutationFunction<SignupMutation, SignupMutationVariables>;

/**
 * __useSignupMutation__
 *
 * To run a mutation, you first call `useSignupMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSignupMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [signupMutation, { data, loading, error }] = useSignupMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useSignupMutation(baseOptions?: Apollo.MutationHookOptions<SignupMutation, SignupMutationVariables>) {
        return Apollo.useMutation<SignupMutation, SignupMutationVariables>(SignupDocument, baseOptions);
      }
export type SignupMutationHookResult = ReturnType<typeof useSignupMutation>;
export type SignupMutationResult = Apollo.MutationResult<SignupMutation>;
export type SignupMutationOptions = Apollo.BaseMutationOptions<SignupMutation, SignupMutationVariables>;