source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in billing.gemspec.
gemspec

group :development do
  gem 'pg'
end

group :test do
  gem 'rspec-rails'
end
